---

- name: Airflow | Ensure airflow directories structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  with_items:
    - "{{ airflow_logs_folder }}"
    - "{{ airflow_child_process_log_folder }}"
    - "{{ airflow_dags_folder }}"
    - "{{ airflow_plugins_folder }}"

- name: Airflow | Copy gunicorn logrotate config
  template:
    src: gunicorn-logrotate.j2
    dest: /etc/logrotate.d/airflow
    mode: 0644
    owner: root
    group: root

- name: Airflow | Copy basic airflow config file
  template:
    src: "{{ airflow_config_template_path }}"
    dest: "{{ airflow_home }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: install SQLAlchemy
  pip:
    name: SQLAlchemy==1.3.15
    executable: "{{ airflow_pip_executable }}"

- name: Airflow | Initializing DB
  command: "{{ airflow_executable }} initdb"
  environment:
    AIRFLOW_HOME: "{{ airflow_home }}"
  become: true
  become_user: "{{ airflow_user }}"
  tags:
    skip_ansible_lint
  when: airflow_install.changed or airflow_config.changed
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Copy extra airflow config files (provided by playbooks)
  copy:
    src: "{{ item }}"
    dest: "{{ airflow_home }}/{{ item | basename }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  with_fileglob:
    - "{{ airflow_extra_conf_path }}/*"
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Copy extra airflow config templates (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ airflow_home }}/{{ item | basename }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  with_fileglob:
    - "{{ airflow_extra_conf_template_path }}/*"
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Add variables from configuration file
  command: "{{ airflow_executable }} variables -s {{ item.key }} {{ item.value }}"
  environment:
    AIRFLOW_HOME: "{{ airflow_home }}"
  become: true
  become_user: "{{ airflow_user }}"
  with_items: "{{ airflow_admin_variables }}"
  tags:
    skip_ansible_lint

- name: Airflow | Add connections from configuration file
  command: "{{ airflow_executable }} connections -a {% for key, value in item.iteritems() %}--{{ key }} '{{ value }}' {% endfor %}"
  environment:
    AIRFLOW_HOME: "{{ airflow_home }}"
  become: true
  become_user: "{{ airflow_user }}"
  with_items: "{{ airflow_admin_connections }}"
  tags:
    skip_ansible_lint
